# docker-compose.yml

version: "3.8"

services:
  taxi-server:
    build:
      context: ./server
    command: python manage.py runserver 0.0.0.0:8000
    container_name: taxi-server
    depends_on:
      - taxi-redis
    environment:
      - REDIS_URL=redis://taxi-redis:6379/0
    ports:
      - 8003:8000

  taxi-redis:
    container_name: taxi-redis
    image: redis:6-alpine
