# Generated by Django 3.1.4 on 2021-09-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20210918_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('STARTED', 'STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMMPLETED', 'COMMPLETED')], default='REQUESTED', max_length=20),
        ),
    ]
